
-- View Table from selected Query and some encoding of data
CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_CR_COST_OAC"
("COM_ID", "PARTY_ID", "PARTY_NAME", "CSL_ID", "ETA_ETD_NO"
, "ETD_POL_D", "POD_ID", "POD", "CNTR_ID", "CNTR_SIZE"
, "CNTR_TYPE", "COST_TERM", "RATE", "ENCODED_TYPE"
, "ENCODED_TERM", "POD_ID_EN") DEFAULT COLLATION "USING_NLS_COMP" 
AS 
	SELECT
	    "COM_ID",
	    "PARTY_ID",
	    "PARTY_NAME",
	    "CSL_ID",
	    "ETA_ETD_NO",
	    "ETD_POL_D",
	    "POD_ID",
	    "POD",
	    "CNTR_ID",
	    "CNTR_SIZE",
	    "CNTR_TYPE",
	    "COST_TERM",
	    "RATE",
	    CASE
	        WHEN CNTR_TYPE = 'HC' THEN 1
	        WHEN CNTR_TYPE = 'GP' THEN 2
	        WHEN CNTR_TYPE = 'GP (SOC)' THEN 3
	        WHEN CNTR_TYPE = 'HC NOR' THEN 4
	        WHEN CNTR_TYPE = 'HC (SOC)' THEN 5
	        WHEN CNTR_TYPE = 'HC (DG)' THEN 6
	    END AS ENCODED_TYPE,
	    CASE
	        WHEN COST_TERM = 'FC' THEN 1
	        WHEN COST_TERM = 'FP' THEN 2
	    END AS ENCODED_TERM,
	    ORA_HASH(POD_ID) AS POD_ID_EN
	FROM OAC_CR_COST
